//! Offline pcap replay over the shipped corpus, through the real capture handle and DLT
//! resolution. Asserts the detections declared in the corpus manifest and, above all, that
//! nothing in the corpus can panic the sensor.
//!
//! The corpus is generated by `sensor/tools/gen_corpus.py`; the Python-vs-Rust
//! deliberate divergences are listed in `sensor/docs/COMPATIBILITY.md` §2.

use std::path::{Path, PathBuf};

use maltrail_sensor::testkit::*;

fn corpus_dir() -> PathBuf {
    // MALTRAIL_CORPUS points this at a corpus built somewhere else - which is what
    // `tools/gen_corpus.py --from-trails` produces: the same cases synthesized from the operator's
    // real 1.6M-row trails.csv rather than the 30 hand-written fixture trails. That mode used to be
    // consumed by the differential harness; without an override it would have had no consumer at
    // all.
    match std::env::var_os("MALTRAIL_CORPUS") {
        Some(dir) => PathBuf::from(dir),
        None => PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests").join("corpus"),
    }
}

/// Minimal manifest reader (name, pcap, expectations, flags) so the tests need no JSON dep.
struct Case {
    name: String,
    pcap: PathBuf,
    expect: Vec<String>,
    needs_pcap_timestamps: bool,
}

fn read_manifest() -> Vec<Case> {
    let path = corpus_dir().join("manifest.json");
    let text = match std::fs::read_to_string(&path) {
        Ok(t) => t,
        Err(_) => return Vec::new(),
    };
    let mut cases = Vec::new();
    let mut current: Option<(String, String, Vec<String>, bool)> = None;
    for line in text.lines() {
        let line = line.trim();
        if line == "{" {
            current = Some((String::new(), String::new(), Vec::new(), false));
        } else if line.starts_with("\"name\":") {
            if let Some(c) = current.as_mut() {
                c.0 = json_string(line);
            }
        } else if line.starts_with("\"pcap\":") {
            if let Some(c) = current.as_mut() {
                c.1 = json_string(line);
            }
        } else if line.starts_with("\"needs_pcap_timestamps\":") {
            if let Some(c) = current.as_mut() {
                c.3 = line.contains("true");
            }
        } else if line.starts_with('"') && line.ends_with("\",") && current.is_some() && line.matches('"').count() == 2
        {
            // a bare string element of the "expect" array
            if let Some(c) = current.as_mut() {
                c.2.push(line.trim_end_matches(',').trim_matches('"').to_string());
            }
        } else if line.starts_with('"') && line.ends_with('"') && current.is_some() && line.matches('"').count() == 2 {
            if let Some(c) = current.as_mut() {
                c.2.push(line.trim_matches('"').to_string());
            }
        } else if line.starts_with('}') {
            if let Some((name, pcap, expect, needs)) = current.take() {
                if !name.is_empty() {
                    cases.push(Case { name, pcap: corpus_dir().join(pcap), expect, needs_pcap_timestamps: needs });
                }
            }
        }
    }
    cases
}

fn json_string(line: &str) -> String {
    let mut parts = line.splitn(2, ':');
    parts.next();
    parts.next().unwrap_or("").trim().trim_end_matches(',').trim().trim_matches('"').to_string()
}

fn corpus_trails() -> Vec<(String, String, String)> {
    let path = corpus_dir().join("trails.csv");
    let Ok(text) = std::fs::read_to_string(path) else { return Vec::new() };
    text.lines()
        .filter(|l| !l.is_empty())
        .filter_map(|l| {
            let mut it = l.splitn(3, ',');
            Some((it.next()?.to_string(), it.next()?.to_string(), it.next()?.to_string()))
        })
        .collect()
}

fn harness_for_corpus(extra: Vec<String>) -> Harness {
    let owned = corpus_trails();
    let borrowed: Vec<(&str, &str, &str)> =
        owned.iter().map(|(a, b, c)| (a.as_str(), b.as_str(), c.as_str())).collect();
    Harness::with_options(
        &borrowed,
        HarnessOptions { use_heuristics: true, check_host_domains: true, check_missing_host: true, extra },
    )
}

#[test]
fn corpus_exists() {
    assert!(!read_manifest().is_empty(), "corpus missing; run: python3 sensor/tools/gen_corpus.py");
}

#[test]
fn every_corpus_case_replays_without_panicking() {
    let cases = read_manifest();
    assert!(!cases.is_empty());
    let mut total_packets = 0usize;
    for case in &cases {
        let mut h = harness_for_corpus(vec!["USE_FAST_PREFILTER true".to_string(), "FAST_FLOW_CUTOFF 4".to_string()]);
        total_packets += h.replay(&case.pcap, false);
        let errors = h.errors();
        assert!(
            errors.iter().all(|e| !e.to_lowercase().contains("panic")),
            "case {} logged a panic: {errors:?}",
            case.name
        );
    }
    assert!(total_packets > 400, "replayed only {total_packets} packets");
}

#[test]
fn corpus_expectations_are_met_with_pcap_timestamps() {
    for case in read_manifest() {
        let mut h = harness_for_corpus(vec!["USE_FAST_PREFILTER true".to_string(), "FAST_FLOW_CUTOFF 4".to_string()]);
        h.replay(&case.pcap, false);
        let events = h.events();
        let text: Vec<String> = events
            .iter()
            .map(|e| {
                format!(
                    "{} {} {} {} {} {} {} {} {}",
                    e.src_ip, e.src_port, e.dst_ip, e.dst_port, e.proto, e.trail_type, e.trail, e.info, e.reference
                )
            })
            .collect();
        for expected in &case.expect {
            assert!(
                text.iter().any(|line| line.contains(expected.as_str())),
                "case {}: expected {expected:?} in {text:?}",
                case.name
            );
        }
    }
}

#[test]
fn timing_heuristics_need_real_timestamps() {
    // The same corpus replayed with wall-clock timestamps (what sensor.py does offline on
    // Python 3) cannot reach the counting heuristics: this documents *why* the parity harness
    // reports those cases as a Rust surplus in --timestamps pcap mode.
    for case in read_manifest().into_iter().filter(|c| c.needs_pcap_timestamps) {
        // Matched against the whole formatted event line, not just `info`: the reader above
        // cannot tell "expect" from "expect_rust_only" strings apart, and a divergence pin may
        // name a TRAIL ("203.0.113.77:443") rather than an info phrase.
        let mut h = harness_for_corpus(vec![]);
        h.replay(&case.pcap, true);
        let events = h.events();
        let lines: Vec<String> =
            events.iter().map(|e| format!("{} {} {} {} {}", e.src_ip, e.dst_ip, e.proto, e.trail, e.info)).collect();
        for expected in &case.expect {
            assert!(
                !lines.iter().any(|line| line.contains(expected.as_str())),
                "case {}: {expected:?} must NOT fire with wall-clock timestamps",
                case.name
            );
        }

        let mut h = harness_for_corpus(vec![]);
        h.replay(&case.pcap, false);
        let events = h.events();
        let lines: Vec<String> =
            events.iter().map(|e| format!("{} {} {} {} {}", e.src_ip, e.dst_ip, e.proto, e.trail, e.info)).collect();
        for expected in &case.expect {
            assert!(
                lines.iter().any(|line| line.contains(expected.as_str())),
                "case {}: {expected:?} must fire with pcap timestamps, got {lines:?}",
                case.name
            );
        }
    }
}

#[test]
fn clean_traffic_produces_no_events() {
    let mut h = harness_for_corpus(vec![]);
    let pcap = corpus_dir().join("clean_tcp.pcap");
    if !pcap.is_file() {
        return;
    }
    h.replay(&pcap, false);
    assert!(h.events().is_empty(), "{:?}", h.events());
}

/// The error log is process-global by design (`output::ERROR_LOG` is a `OnceLock`, mirroring
/// `core/log.py`'s single error log), so the FIRST harness in a test binary owns the file every
/// later harness also writes to. Any test that asserts "nothing was logged" therefore has to
/// exclude the tests that log on purpose — otherwise it passes or fails on thread scheduling.
static ERROR_LOG_EXCLUSIVE: std::sync::Mutex<()> = std::sync::Mutex::new(());

#[test]
fn truncated_corpus_case_is_silent_and_error_free() {
    let _exclusive = ERROR_LOG_EXCLUSIVE.lock().unwrap_or_else(|e| e.into_inner());
    let mut h = harness_for_corpus(vec![]);
    let pcap = corpus_dir().join("truncated.pcap");
    if !pcap.is_file() {
        return;
    }
    // Start from a known-empty log: an earlier test in this binary may already have written to
    // whichever file won the OnceLock.
    let _ = std::fs::write(h.log_dir().join("error.log"), "");
    h.replay(&pcap, false);
    assert!(h.events().is_empty(), "{:?}", h.events());
    assert!(h.errors().is_empty(), "{:?}", h.errors());
}

#[test]
fn replay_is_deterministic() {
    let pcap = corpus_dir().join("mixed_soup.pcap");
    if !pcap.is_file() {
        return;
    }
    let run = || -> Vec<String> {
        let mut h = harness_for_corpus(vec![]);
        h.replay(&pcap, false);
        h.events()
            .into_iter()
            .map(|e| format!("{} {} {} {} {}", e.src_ip, e.dst_ip, e.trail_type, e.trail, e.info))
            .collect()
    };
    assert_eq!(run(), run(), "the same pcap must yield the same events every run");
}

#[test]
fn multiple_pcaps_in_one_worker_share_state() {
    // Several files replayed through one worker must behave like one stream (this is what
    // `-r a.pcap,b.pcap` does).
    let a = corpus_dir().join("dns_queries.pcap");
    let b = corpus_dir().join("ip_trails.pcap");
    if !a.is_file() || !b.is_file() {
        return;
    }
    let mut h = harness_for_corpus(vec![]);
    let n = h.replay(&a, false) + h.replay(&b, false);
    assert!(n > 5);
    assert!(!h.events().is_empty());
}

#[test]
fn unknown_datalink_falls_back_to_the_offset_heuristic() {
    // This one logs on purpose ("unexpected datalink"), into the shared process-global error
    // log — so it must not overlap the test that asserts the log is empty.
    let _exclusive = ERROR_LOG_EXCLUSIVE.lock().unwrap_or_else(|e| e.into_inner());
    // Write a pcap with an exotic linktype and confirm the learner still finds the IP header.
    let dir = std::env::temp_dir().join("mt-replay-dlt");
    std::fs::create_dir_all(&dir).unwrap();
    let path = dir.join("exotic.pcap");
    let inner = ipv4(6, "10.0.0.5", "66.66.66.66", &tcp(50000, 443, 0x02, b""));
    // 6-byte pseudo link header in front of the IP packet, linktype 147 (USER0)
    let mut frame = vec![0xde, 0xad, 0xbe, 0xef, 0x00, 0x00];
    frame.extend_from_slice(&inner);
    write_pcap(&path, 147, &[(1, frame.clone()), (2, frame)]);

    let mut h = Harness::new(&[("66.66.66.66", "badnet", "ref")]);
    let n = h.replay(&path, false);
    assert_eq!(n, 2);
    assert_eq!(h.trails(), vec!["66.66.66.66", "66.66.66.66"]);
    let _ = std::fs::remove_dir_all(&dir);
}

fn write_pcap(path: &Path, linktype: u32, packets: &[(u32, Vec<u8>)]) {
    use std::io::Write;
    let mut f = std::fs::File::create(path).unwrap();
    f.write_all(&0xa1b2c3d4u32.to_le_bytes()).unwrap();
    f.write_all(&2u16.to_le_bytes()).unwrap();
    f.write_all(&4u16.to_le_bytes()).unwrap();
    f.write_all(&0i32.to_le_bytes()).unwrap();
    f.write_all(&0u32.to_le_bytes()).unwrap();
    f.write_all(&65535u32.to_le_bytes()).unwrap();
    f.write_all(&linktype.to_le_bytes()).unwrap();
    for (ts, data) in packets {
        f.write_all(&ts.to_le_bytes()).unwrap();
        f.write_all(&0u32.to_le_bytes()).unwrap();
        f.write_all(&(data.len() as u32).to_le_bytes()).unwrap();
        f.write_all(&(data.len() as u32).to_le_bytes()).unwrap();
        f.write_all(data).unwrap();
    }
}
