#!/usr/bin/env python3
# coding: utf-8
"""Generate sensor/src/settings_gen.rs from core/settings.py.

The sensor's detection behaviour depends on long, fiddly regexes and keyword tuples that
live in core/settings.py. Transcribing them by hand into Rust would be a silent-drift
hazard, so they are *generated* straight from the Python module: run this after changing
core/settings.py and the Rust sensor picks the change up.

    python3 sensor/tools/gen_settings.py

Deterministic: Python sets are emitted sorted, tuples/lists keep their order (which is
load-bearing for the "first regex wins" scans).
"""

import argparse
import io
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
OUT = os.path.join(ROOT, "sensor", "src", "settings_gen.rs")

sys.path.insert(0, ROOT)

from core import settings as S  # noqa: E402


_ESCAPES = {"\\": "\\\\", '"': '\\"', "\r": "\\r", "\n": "\\n", "\t": "\\t", "\0": "\\0"}


def rust_str(value):
    """Emit a Rust string literal for `value`.

    Values with control characters must use a normal (escaped) literal - a raw literal
    would embed a real newline/CR in the generated source. Everything else uses a raw
    literal so the many regex backslashes stay readable and unambiguous.
    """
    if any(ord(_) < 0x20 for _ in value):
        out = []
        for ch in value:
            if ch in _ESCAPES:
                out.append(_ESCAPES[ch])
            elif ord(ch) < 0x20:
                out.append("\\u{%x}" % ord(ch))
            else:
                out.append(ch)
        return '"%s"' % "".join(out)

    if "\\" in value or '"' in value:
        hashes = 1
        while ('"' + "#" * hashes) in value:
            hashes += 1
        guard = "#" * hashes
        if value.endswith('"'):
            guard = "#" * (hashes + 1)
        return 'r%s"%s"%s' % (guard, value, guard)
    return '"%s"' % value


def emit_str_slice(name, items, comment=None):
    out = []
    if comment:
        out.append("/// %s" % comment)
    out.append("pub const %s: &[&str] = &[" % name)
    for item in items:
        out.append("    %s," % rust_str(item))
    out.append("];")
    return "\n".join(out)


def emit_pairs(name, pairs, comment=None):
    out = []
    if comment:
        out.append("/// %s" % comment)
    out.append("pub const %s: &[(&str, &str)] = &[" % name)
    for a, b in pairs:
        out.append("    (%s, %s)," % (rust_str(a), rust_str(b)))
    out.append("];")
    return "\n".join(out)


def main(out_path=None):
    S.read_ua()  # builds SUSPICIOUS_UA_REGEX from data/ua.txt

    import socket
    ipproto = sorted(((getattr(socket, _), _.replace("IPPROTO_", "")) for _ in dir(socket) if _.startswith("IPPROTO_")))
    # dict() semantics: later duplicates win, mirroring core/settings.py:IPPROTO_LUT
    lut = {}
    for num, name in ipproto:
        lut[num] = name

    chunks = [
        "//! GENERATED by sensor/tools/gen_settings.py from core/settings.py.",
        "//! Do not edit by hand; re-run the generator instead.",
        "//!",
        "//! Every item here is a verbatim copy of the Python constant of the same name, so",
        "//! detection semantics cannot silently drift between the two sensors.",
        "#![allow(clippy::all)]",
        "",
        "pub const VERSION: &str = %s;" % rust_str(S.VERSION),
        "pub const NAME: &str = %s;" % rust_str(S.NAME),
        "pub const HOMEPAGE: &str = %s;" % rust_str(S.HOMEPAGE),
        "pub const TIME_FORMAT: &str = %s;" % rust_str(S.TIME_FORMAT),
        "pub const HTTP_TIME_FORMAT: &str = %s;" % rust_str(S.HTTP_TIME_FORMAT),
        "pub const CEF_FORMAT: &str = %s;" % rust_str(S.CEF_FORMAT),
        "pub const SNAP_LEN: usize = %d;" % S.SNAP_LEN,
        "pub const CAPTURE_TIMEOUT_MS: i32 = %d;" % S.CAPTURE_TIMEOUT,
        "pub const MAX_CACHE_ENTRIES: usize = %d;" % S.MAX_CACHE_ENTRIES,
        "pub const PORT_SCANNING_THRESHOLD: usize = %d;" % S.PORT_SCANNING_THRESHOLD,
        "pub const WEB_SCANNING_THRESHOLD: usize = %d;" % S.WEB_SCANNING_THRESHOLD,
        "pub const INFECTION_SCANNING_THRESHOLD: usize = %d;" % S.INFECTION_SCANNING_THRESHOLD,
        "pub const DNS_EXHAUSTION_THRESHOLD: usize = %d;" % S.DNS_EXHAUSTION_THRESHOLD,
        "pub const NO_SUCH_NAME_PER_HOUR_THRESHOLD: u32 = %d;" % S.NO_SUCH_NAME_PER_HOUR_THRESHOLD,
        "pub const SUSPICIOUS_DOMAIN_LENGTH_THRESHOLD: usize = %d;" % S.SUSPICIOUS_DOMAIN_LENGTH_THRESHOLD,
        "",
        "/// DNS tunnelling: every one of these must hold at once, which is the point - see core/settings.py",
        "pub const DNS_TUNNELING_MIN_QUERIES: usize = %d;" % S.DNS_TUNNELING_MIN_QUERIES,
        "pub const DNS_TUNNELING_MIN_DISTINCT_PCT: usize = %d;" % S.DNS_TUNNELING_MIN_DISTINCT_PCT,
        "pub const DNS_TUNNELING_MIN_LONG_PCT: usize = %d;" % S.DNS_TUNNELING_MIN_LONG_PCT,
        "pub const DNS_TUNNELING_MIN_LABEL: usize = %d;" % S.DNS_TUNNELING_MIN_LABEL,
        "pub const DNS_TUNNELING_MIN_ENTROPY_X100: u32 = %d;" % S.DNS_TUNNELING_MIN_ENTROPY_X100,
        "pub const DNS_TUNNELING_MIN_BYTES: usize = %d;" % S.DNS_TUNNELING_MIN_BYTES,
        "pub const DNS_TUNNELING_MIN_SPAN: u64 = %d;" % S.DNS_TUNNELING_MIN_SPAN,
        "pub const DNS_TUNNELING_WINDOW: u64 = %d;" % S.DNS_TUNNELING_WINDOW,
        "pub const SUSPICIOUS_DOMAIN_CONSONANT_THRESHOLD: usize = %d;" % S.SUSPICIOUS_DOMAIN_CONSONANT_THRESHOLD,
        "pub const SUSPICIOUS_DOMAIN_ENTROPY_THRESHOLD: f64 = %r;" % S.SUSPICIOUS_DOMAIN_ENTROPY_THRESHOLD,
        "pub const HOURLY_SECS: u64 = %d;" % S.HOURLY_SECS,
        "pub const CONDENSED_EVENTS_FLUSH_PERIOD: u64 = %d;" % S.CONDENSED_EVENTS_FLUSH_PERIOD,
        "pub const MAX_CONDENSED_EVENTS: usize = %d;" % S.MAX_CONDENSED_EVENTS,
        "pub const META_DB_FILENAME: &str = %s;" % rust_str(S.META_DB_FILENAME),
        "pub const CONDENSED_FLUSH_PERIOD: u64 = %d;" % S.CONDENSED_FLUSH_PERIOD,
        "pub const CONDENSED_MAX_WINDOW_KEYS: usize = %d;" % S.CONDENSED_MAX_WINDOW_KEYS,
        "pub const META_MAX_ROWS: usize = %d;" % S.META_MAX_ROWS,
        "pub const CONSONANTS: &str = %s;" % rust_str(S.CONSONANTS),
        "pub const VALID_DNS_NAME_REGEX: &str = %s;" % rust_str(S.VALID_DNS_NAME_REGEX),
        "pub const SUSPICIOUS_DIRECT_IP_URL_REGEX: &str = %s;" % rust_str(S.SUSPICIOUS_DIRECT_IP_URL_REGEX),
        "pub const GENERIC_SINKHOLE_REGEX: &str = %s;" % rust_str(S.GENERIC_SINKHOLE_REGEX),
        "pub const WHITELIST_UA_REGEX: &str = %s;" % rust_str(S.WHITELIST_UA_REGEX),
        "",
        "/// POTENTIAL_INFECTION_PORTS",
        "pub const POTENTIAL_INFECTION_PORTS: &[u16] = &[%s];" % ", ".join(str(_) for _ in S.POTENTIAL_INFECTION_PORTS),
        "",
        "/// _STEALTH_FLAGS from sensor.py (NULL / bare-FIN / XMAS scans)",
        "pub const STEALTH_FLAGS: &[u8] = &[0x00, 0x01, 0x29];",
        "",
        emit_str_slice("IGNORE_DNS_QUERY_SUFFIXES", sorted(S.IGNORE_DNS_QUERY_SUFFIXES)),
        "",
        emit_str_slice("SUSPICIOUS_CONTENT_TYPES", list(S.SUSPICIOUS_CONTENT_TYPES)),
        "",
        emit_str_slice("SUSPICIOUS_DIRECT_DOWNLOAD_EXTENSIONS", sorted(S.SUSPICIOUS_DIRECT_DOWNLOAD_EXTENSIONS)),
        "",
        emit_str_slice("WHITELIST_DIRECT_DOWNLOAD_KEYWORDS", list(S.WHITELIST_DIRECT_DOWNLOAD_KEYWORDS)),
        "",
        emit_str_slice("SUSPICIOUS_HTTP_REQUEST_PRE_CONDITION", list(S.SUSPICIOUS_HTTP_REQUEST_PRE_CONDITION)),
        "",
        emit_str_slice("SUSPICIOUS_PROXY_PROBE_PRE_CONDITION", list(S.SUSPICIOUS_PROXY_PROBE_PRE_CONDITION)),
        "",
        emit_str_slice("WHITELIST_HTTP_REQUEST_PATHS", list(S.WHITELIST_HTTP_REQUEST_PATHS)),
        "",
        emit_str_slice("WHITELIST_LONG_DOMAIN_NAME_KEYWORDS", list(S.WHITELIST_LONG_DOMAIN_NAME_KEYWORDS)),
        emit_str_slice("HASH_LABEL_SERVICE_ZONES", list(S.HASH_LABEL_SERVICE_ZONES)),
        "",
        emit_str_slice("LOCAL_SUBDOMAIN_LOOKUPS", list(S.LOCAL_SUBDOMAIN_LOOKUPS)),
        "",
        emit_str_slice("CONDENSE_ON_INFO_KEYWORDS", list(S.CONDENSE_ON_INFO_KEYWORDS)),
        "",
        emit_str_slice("KNOWN_CONFIG_OPTIONS", sorted(S.KNOWN_CONFIG_OPTIONS),
                       comment="Every option name any parser accepts; an unlisted name in maltrail.conf is a typo"),
        "",
        emit_pairs("SUSPICIOUS_HTTP_REQUEST_REGEXES", list(S.SUSPICIOUS_HTTP_REQUEST_REGEXES),
                   "(description, regex) - scanned in order; the FIRST match wins"),
        "",
        emit_pairs("SUSPICIOUS_HTTP_PATH_REGEXES", list(S.SUSPICIOUS_HTTP_PATH_REGEXES)),
        "",
        emit_pairs("SUSPICIOUS_HTTP_REQUEST_FORCE_ENCODE_CHARS",
                   list(S.SUSPICIOUS_HTTP_REQUEST_FORCE_ENCODE_CHARS.items()),
                   "(char, percent-encoding) applied to path/post_data before logging"),
        "",
        "/// SUSPICIOUS_UA_REGEX, built by core/settings.py:read_ua() from data/ua.txt",
        "/// (each line kept verbatim if it compiles as a regex, else re.escape()d; lines",
        "/// containing \" (compatible\" are always escaped).",
        "pub const SUSPICIOUS_UA_REGEX: &str = %s;" % rust_str(S.SUSPICIOUS_UA_REGEX),
        "",
        "/// DLT_OFFSETS (core/settings.py, resolved for this platform)",
        "pub const DLT_OFFSETS: &[(i32, usize)] = &[%s];"
        % ", ".join("(%d, %d)" % (k, v) for k, v in sorted(S.DLT_OFFSETS.items())),
        "",
        "/// IPPROTO_LUT (protocol number -> Maltrail protocol label)",
        "pub const IPPROTO_LUT: &[(u8, &str)] = &[%s];"
        % ", ".join('(%d, "%s")' % (k, v) for k, v in sorted(lut.items()) if k <= 255),
        "",
    ]

    content = "\n".join(chunks)
    target = out_path or OUT
    with open(target, "w") as f:
        f.write(content)
    print("[i] wrote %s (%d bytes)" % (target, len(content)))


def _constants(text):
    """{name: normalised value} for every `pub const` in a settings_gen.rs.

    The checked-in file is rustfmt'd and this generator's output is not, so the two are never
    byte-equal even when they carry identical constants: rustfmt re-wraps the slices and adds a
    trailing comma to every one it breaks across lines. Comparing NAME -> value with the formatting
    removed asks the only question that matters, and needs no rustfmt to answer it.

    Removing it means ALL whitespace outside string literals, plus a comma before a closing bracket.
    Collapsing runs of whitespace to one space is not enough - that was the first attempt, and it
    called a perfectly current file stale in 10 constants, which is the same "gate cries wolf on a
    healthy tree" failure this session has now fixed twice elsewhere.

    >>> a = _constants('pub const X: &[&str] = &["a", "b"];\\n')
    >>> b = _constants('pub const X: &[&str] = &[\\n    "a",\\n    "b",\\n];\\n')
    >>> a == b
    True
    >>> _constants('pub const X: &str = "a b";\\n') == _constants('pub const X: &str = "ab";\\n')
    False
    """

    found = {}
    for match in re.finditer(r"pub const (\w+)\s*:[^=]*=\s*(.*?);\n", text, re.S):
        name, value = match.group(1), match.group(2)

        # Split on string literals so whitespace INSIDE a literal (" " in a keyword list, "\n" in a
        # regex) is never touched; only the layout between tokens is.
        parts = re.split(r'(r?#*"(?:[^"\\]|\\.)*"#*)', value)
        for i in range(0, len(parts), 2):
            parts[i] = re.sub(r"\s+", "", parts[i]).replace(",]", "]").replace(",)", ")")
        found[name] = "".join(parts)

    return found


def check(out_path=None):
    """Is the checked-in settings_gen.rs current with core/settings.py + data/ua.txt? Writes nothing.

    `cargo test --test generated` remains the authority in CI (it compares what the sensor actually
    COMPILED). This is the same question answerable in a second, without a toolchain - and without the
    trap that produced it: `--check` used to be an unrecognised argument, silently ignored, so a
    read-only-sounding flag rewrote the working tree instead of reporting on it.
    """

    target = out_path or OUT
    try:
        with open(target) as f:
            on_disk = _constants(f.read())
    except EnvironmentError as ex:
        print("[x] cannot read %s (%s)" % (target, ex))
        return 1

    import contextlib
    import tempfile
    handle, tmp = tempfile.mkstemp(suffix=".rs")
    os.close(handle)
    try:
        with contextlib.redirect_stdout(io.StringIO()):   # main() announces the write; a check has not written anything
            main(tmp)
        with open(tmp) as f:
            fresh = _constants(f.read())
    finally:
        try:
            os.remove(tmp)
        except OSError:
            pass

    drift = sorted(set(fresh) ^ set(on_disk)) + sorted(k for k in set(fresh) & set(on_disk) if fresh[k] != on_disk[k])
    if not drift:
        print("[i] %s is current (%d constants)" % (target, len(fresh)))
        return 0

    print("[!] %s is STALE: %d constant(s) differ" % (target, len(drift)))
    for name in drift[:10]:
        if name not in on_disk:
            print("      %s: missing from the checked-in file" % name)
        elif name not in fresh:
            print("      %s: no longer generated" % name)
        else:
            print("      %s: %.60s... != %.60s..." % (name, on_disk[name], fresh[name]))
    if len(drift) > 10:
        print("      ... and %d more" % (len(drift) - 10))
    print("[?] regenerate with:")
    print("[?]     python3 sensor/tools/gen_settings.py")
    print("[?]     rustfmt --edition 2021 --config-path sensor/rustfmt.toml sensor/src/settings_gen.rs")
    return 1


def require_supported_interpreter():
    """Refuse to generate (or judge) on an interpreter that produces a different file.

    `sensor/tools/check.sh` already requires 3.7+ before it runs this, "because a generator run on an
    older interpreter can emit a subtly wrong settings_gen.rs rather than failing". Running the
    generator directly bypassed that. It is not theoretical: on 3.6 this reports IPPROTO_LUT and
    SUSPICIOUS_UA_REGEX as stale, because IPPROTO_LUT is built from `dir(socket)` and that set differs
    between interpreter versions - and the advice a STALE verdict prints would then have you write the
    wrong file. The server still supports 3.6; generating this Rust source does not.
    """

    if sys.version_info[:2] < (3, 7):
        print("[!] python3 is %d.%d.%d, but generating settings_gen.rs needs 3.7+" % sys.version_info[:3])
        print("[?] IPPROTO_LUT comes from dir(socket), which differs between versions - an older")
        print("[?] interpreter writes a subtly different file rather than failing. Use the same")
        print("[?] interpreter CI does (see sensor/tools/check.sh, which enforces this before it runs).")
        return False

    return True


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate sensor/src/settings_gen.rs from core/settings.py.")
    # `-o PATH` writes elsewhere, so a freshness test can regenerate into a temp file and diff
    # against the checked-in one without touching the tree.
    parser.add_argument("-o", "--out", dest="out", default=None, help="write here instead of the default path")
    parser.add_argument("--check", action="store_true", help="report whether the checked-in file is current; write nothing")
    options = parser.parse_args()      # argparse, so an unrecognised flag is an ERROR rather than a silent write

    if not require_supported_interpreter():
        sys.exit(2)

    sys.exit(check(options.out) if options.check else main(options.out) or 0)
