#!/usr/bin/env python3
# coding: utf-8
"""Generate sensor/src/settings_gen.rs from core/settings.py.

The sensor's detection behaviour depends on long, fiddly regexes and keyword tuples that
live in core/settings.py. Transcribing them by hand into Rust would be a silent-drift
hazard, so they are *generated* straight from the Python module: run this after changing
core/settings.py and the Rust sensor picks the change up.

    python3 sensor/tools/gen_settings.py

Deterministic: Python sets are emitted sorted, tuples/lists keep their order (which is
load-bearing for the "first regex wins" scans).
"""
from __future__ import print_function

import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
OUT = os.path.join(ROOT, "sensor", "src", "settings_gen.rs")

sys.path.insert(0, ROOT)

from core import settings as S  # noqa: E402


_ESCAPES = {"\\": "\\\\", '"': '\\"', "\r": "\\r", "\n": "\\n", "\t": "\\t", "\0": "\\0"}


def rust_str(value):
    """Emit a Rust string literal for `value`.

    Values with control characters must use a normal (escaped) literal - a raw literal
    would embed a real newline/CR in the generated source. Everything else uses a raw
    literal so the many regex backslashes stay readable and unambiguous.
    """
    if any(ord(_) < 0x20 for _ in value):
        out = []
        for ch in value:
            if ch in _ESCAPES:
                out.append(_ESCAPES[ch])
            elif ord(ch) < 0x20:
                out.append("\\u{%x}" % ord(ch))
            else:
                out.append(ch)
        return '"%s"' % "".join(out)

    if "\\" in value or '"' in value:
        hashes = 1
        while ('"' + "#" * hashes) in value:
            hashes += 1
        guard = "#" * hashes
        if value.endswith('"'):
            guard = "#" * (hashes + 1)
        return 'r%s"%s"%s' % (guard, value, guard)
    return '"%s"' % value


def emit_str_slice(name, items, comment=None):
    out = []
    if comment:
        out.append("/// %s" % comment)
    out.append("pub const %s: &[&str] = &[" % name)
    for item in items:
        out.append("    %s," % rust_str(item))
    out.append("];")
    return "\n".join(out)


def emit_pairs(name, pairs, comment=None):
    out = []
    if comment:
        out.append("/// %s" % comment)
    out.append("pub const %s: &[(&str, &str)] = &[" % name)
    for a, b in pairs:
        out.append("    (%s, %s)," % (rust_str(a), rust_str(b)))
    out.append("];")
    return "\n".join(out)


def main(out_path=None):
    S.read_ua()  # builds SUSPICIOUS_UA_REGEX from misc/ua.txt

    import socket
    ipproto = sorted(((getattr(socket, _), _.replace("IPPROTO_", "")) for _ in dir(socket) if _.startswith("IPPROTO_")))
    # dict() semantics: later duplicates win, mirroring core/settings.py:IPPROTO_LUT
    lut = {}
    for num, name in ipproto:
        lut[num] = name

    chunks = [
        "//! GENERATED by sensor/tools/gen_settings.py from core/settings.py.",
        "//! Do not edit by hand; re-run the generator instead.",
        "//!",
        "//! Every item here is a verbatim copy of the Python constant of the same name, so",
        "//! detection semantics cannot silently drift between the two sensors.",
        "#![allow(clippy::all)]",
        "",
        "pub const VERSION: &str = %s;" % rust_str(S.VERSION),
        "pub const NAME: &str = %s;" % rust_str(S.NAME),
        "pub const HOMEPAGE: &str = %s;" % rust_str(S.HOMEPAGE),
        "pub const TIME_FORMAT: &str = %s;" % rust_str(S.TIME_FORMAT),
        "pub const HTTP_TIME_FORMAT: &str = %s;" % rust_str(S.HTTP_TIME_FORMAT),
        "pub const CEF_FORMAT: &str = %s;" % rust_str(S.CEF_FORMAT),
        "pub const SNAP_LEN: usize = %d;" % S.SNAP_LEN,
        "pub const CAPTURE_TIMEOUT_MS: i32 = %d;" % S.CAPTURE_TIMEOUT,
        "pub const MAX_CACHE_ENTRIES: usize = %d;" % S.MAX_CACHE_ENTRIES,
        "pub const PORT_SCANNING_THRESHOLD: usize = %d;" % S.PORT_SCANNING_THRESHOLD,
        "pub const WEB_SCANNING_THRESHOLD: usize = %d;" % S.WEB_SCANNING_THRESHOLD,
        "pub const INFECTION_SCANNING_THRESHOLD: usize = %d;" % S.INFECTION_SCANNING_THRESHOLD,
        "pub const DNS_EXHAUSTION_THRESHOLD: usize = %d;" % S.DNS_EXHAUSTION_THRESHOLD,
        "pub const NO_SUCH_NAME_PER_HOUR_THRESHOLD: u32 = %d;" % S.NO_SUCH_NAME_PER_HOUR_THRESHOLD,
        "pub const SUSPICIOUS_DOMAIN_LENGTH_THRESHOLD: usize = %d;" % S.SUSPICIOUS_DOMAIN_LENGTH_THRESHOLD,
        "pub const SUSPICIOUS_DOMAIN_CONSONANT_THRESHOLD: usize = %d;" % S.SUSPICIOUS_DOMAIN_CONSONANT_THRESHOLD,
        "pub const SUSPICIOUS_DOMAIN_ENTROPY_THRESHOLD: f64 = %r;" % S.SUSPICIOUS_DOMAIN_ENTROPY_THRESHOLD,
        "pub const HOURLY_SECS: u64 = %d;" % S.HOURLY_SECS,
        "pub const CONDENSED_EVENTS_FLUSH_PERIOD: u64 = %d;" % S.CONDENSED_EVENTS_FLUSH_PERIOD,
        "pub const MAX_CONDENSED_EVENTS: usize = %d;" % S.MAX_CONDENSED_EVENTS,
        "pub const CONSONANTS: &str = %s;" % rust_str(S.CONSONANTS),
        "pub const VALID_DNS_NAME_REGEX: &str = %s;" % rust_str(S.VALID_DNS_NAME_REGEX),
        "pub const SUSPICIOUS_DIRECT_IP_URL_REGEX: &str = %s;" % rust_str(S.SUSPICIOUS_DIRECT_IP_URL_REGEX),
        "pub const GENERIC_SINKHOLE_REGEX: &str = %s;" % rust_str(S.GENERIC_SINKHOLE_REGEX),
        "pub const WHITELIST_UA_REGEX: &str = %s;" % rust_str(S.WHITELIST_UA_REGEX),
        "",
        "/// POTENTIAL_INFECTION_PORTS",
        "pub const POTENTIAL_INFECTION_PORTS: &[u16] = &[%s];" % ", ".join(str(_) for _ in S.POTENTIAL_INFECTION_PORTS),
        "",
        "/// _STEALTH_FLAGS from sensor.py (NULL / bare-FIN / XMAS scans)",
        "pub const STEALTH_FLAGS: &[u8] = &[0x00, 0x01, 0x29];",
        "",
        emit_str_slice("IGNORE_DNS_QUERY_SUFFIXES", sorted(S.IGNORE_DNS_QUERY_SUFFIXES)),
        "",
        emit_str_slice("SUSPICIOUS_CONTENT_TYPES", list(S.SUSPICIOUS_CONTENT_TYPES)),
        "",
        emit_str_slice("SUSPICIOUS_DIRECT_DOWNLOAD_EXTENSIONS", sorted(S.SUSPICIOUS_DIRECT_DOWNLOAD_EXTENSIONS)),
        "",
        emit_str_slice("WHITELIST_DIRECT_DOWNLOAD_KEYWORDS", list(S.WHITELIST_DIRECT_DOWNLOAD_KEYWORDS)),
        "",
        emit_str_slice("SUSPICIOUS_HTTP_REQUEST_PRE_CONDITION", list(S.SUSPICIOUS_HTTP_REQUEST_PRE_CONDITION)),
        "",
        emit_str_slice("SUSPICIOUS_PROXY_PROBE_PRE_CONDITION", list(S.SUSPICIOUS_PROXY_PROBE_PRE_CONDITION)),
        "",
        emit_str_slice("WHITELIST_HTTP_REQUEST_PATHS", list(S.WHITELIST_HTTP_REQUEST_PATHS)),
        "",
        emit_str_slice("WHITELIST_LONG_DOMAIN_NAME_KEYWORDS", list(S.WHITELIST_LONG_DOMAIN_NAME_KEYWORDS)),
        "",
        emit_str_slice("LOCAL_SUBDOMAIN_LOOKUPS", list(S.LOCAL_SUBDOMAIN_LOOKUPS)),
        "",
        emit_str_slice("CONDENSE_ON_INFO_KEYWORDS", list(S.CONDENSE_ON_INFO_KEYWORDS)),
        "",
        emit_pairs("SUSPICIOUS_HTTP_REQUEST_REGEXES", list(S.SUSPICIOUS_HTTP_REQUEST_REGEXES),
                   "(description, regex) - scanned in order; the FIRST match wins"),
        "",
        emit_pairs("SUSPICIOUS_HTTP_PATH_REGEXES", list(S.SUSPICIOUS_HTTP_PATH_REGEXES)),
        "",
        emit_pairs("SUSPICIOUS_HTTP_REQUEST_FORCE_ENCODE_CHARS",
                   list(S.SUSPICIOUS_HTTP_REQUEST_FORCE_ENCODE_CHARS.items()),
                   "(char, percent-encoding) applied to path/post_data before logging"),
        "",
        "/// SUSPICIOUS_UA_REGEX, built by core/settings.py:read_ua() from misc/ua.txt",
        "/// (each line kept verbatim if it compiles as a regex, else re.escape()d; lines",
        "/// containing \" (compatible\" are always escaped).",
        "pub const SUSPICIOUS_UA_REGEX: &str = %s;" % rust_str(S.SUSPICIOUS_UA_REGEX),
        "",
        "/// DLT_OFFSETS (core/settings.py, resolved for this platform)",
        "pub const DLT_OFFSETS: &[(i32, usize)] = &[%s];"
        % ", ".join("(%d, %d)" % (k, v) for k, v in sorted(S.DLT_OFFSETS.items())),
        "",
        "/// IPPROTO_LUT (protocol number -> Maltrail protocol label)",
        "pub const IPPROTO_LUT: &[(u8, &str)] = &[%s];"
        % ", ".join('(%d, "%s")' % (k, v) for k, v in sorted(lut.items()) if k <= 255),
        "",
    ]

    content = "\n".join(chunks)
    target = out_path or OUT
    with open(target, "w") as f:
        f.write(content)
    print("[i] wrote %s (%d bytes)" % (target, len(content)))


if __name__ == "__main__":
    import sys as _sys
    # `-o PATH` writes elsewhere, so a freshness test can regenerate into a temp file and diff
    # against the checked-in one without touching the tree.
    _out = None
    if len(_sys.argv) >= 3 and _sys.argv[1] == "-o":
        _out = _sys.argv[2]
    main(_out)
